# Generated by Django 4.2.8 on 2024-01-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
